Repository Codo-Baggins/refactor_tractor_fitlit, pull requests merged in 2020-10, with the labels that each got.

#7 Feature/create super class
  src/Activity.js
  src/Health-monitor.js
  src/Hydration.js
  src/Sleep.js
  src/User-repo.js
  test/activity-test.js
  test/health-monitor-test.js
  test/hydration-test.js
  test/sleep-test.js
Labels: refactor

#12 Refactor/accessibility
  src/css/style.scss
  src/index.html
  src/scripts.js
Labels: bug, refactor

#19 Feature Fetch API Data
  src/Activity.js
  src/Health-monitor.js
  src/Sleep.js
  src/css/style.scss
  src/index.html
  src/scripts.js
Labels: bug, enhancement
