Repository Codo-Baggins/refactor_tractor_fitlit, pull requests merged in 2020-11, with the labels that each got.

#24 Refactor - Scripts File Cleanup
  src/scripts.js
Labels: refactor

#26 Feature/chai spies
  src/Activity.js
  src/Health-monitor.js
  src/Sleep.js
  src/User-repo.js
  src/display_object.js
  src/scripts.js
  test/dom-test.js
Labels: bug, enhancement, refactor

#28 Refactor - cleanout unused code
  src/Activity.js
  src/Sleep.js
  src/User-repo.js
  src/scripts.js
  test/activity-test.js
  test/dom-test.js
  test/sleep-test.js
  test/userrepo-test.js
Labels: Delete/Remove, refactor
